triggers:
   - name: triggerv2sp1
     type: trigger
     version:
       counter: 6
       
   - name: triggerv2sp2
     type: trigger
     version:
       counter: 1
       
   - name: triggerv2sp3
     type: trigger
     version:
       counter: 1
