triggers:
   - name: triggerv2sp1
     type: trigger
     version:
       counter: 702
   - name: triggerv2sp2
     type: trigger
     version:
       counter: 177
       
   - name: triggerv2sp3
     type: trigger
     version:
       counter: 165
