jobs:
  - name: plv2-man5
    type: manifest
    steps:
      - IN: plv2-image12
      #- IN: plv2-envimage
      - IN: plv2-params1
       # applyTo:
        #  - plv2-envimage
    #  - IN: flecs-dopts5
     # - IN: infra-repo
      - IN: triggerv2sp1
    #  - IN: varsha
    #on_success:
     # - echo 'this is on_success step of dv-man of type manifest'
    #on_failure:
     # - echo 'this is on_failure step of dv-man of type manifest'
     
  - name: plv2dcl-man1
    type: manifest
    steps:
      - IN: plv2-image12
     # - IN: infra-repo
      - IN: triggerv2sp2
      
  - name: plv2dcl2-manifest
    type: manifest
    steps:
      - IN: plv2-image12
     # - IN: infra-repo
      - IN: triggerv2sp3
        
  - name: dcl-deployinvalid
    type: deploy
    steps:
      - IN: plv2dcl2-manifest 
      - IN: cluster-dclinavlid
  
  - name: release-versionn5
    type: release
    steps:
      - IN: plv2-version
      - IN: plv2-man5
      #- IN: triggerv2sp2
      - TASK: managed
    #  bump: major
          
  - name: plv2-ddcdeployn5
    type: deploy
    steps:
      - IN: plv2-man5
      - IN: ddc-cluster
      - IN: plv2-scale2
      
  - name: b-mon-dcl109n
    type: deploy
    steps:
      - IN: plv2-man5  
      - IN: cluster-dcl
      - TASK: managed
      
  - name: dcl-deployvault7
    type: deploy
    steps:
      - IN: plv2dcl-man1
      - IN: cluster-dcl
      - TASK: managed

  - name: plv2-ecsdeploy6
    type: deploy
    steps:
      - IN: plv2-man5
      - IN: ecs-cluster
     # - IN: glab-kickstart
      - TASK: managed
        #deployMethod: upgrade
    on_success:
      - NOTIFY: myEmail
    on_failure:
      - NOTIFY: myEmail
        #versionNumber: 700


  - name: plv2-gkedeployn6
    type: deploy
    steps:
      - IN: plv2-man5
      - IN: gke-cluster
     # - IN: glab-kickstart
      - IN: plv2-scale2
      - IN: plv2-dopts1
      - TASK: managed
       # deployMethod: upgrade

  - name: plv2-tripubdeployP4
    type: deploy
    steps: 
      - IN: foo-resource
      - IN: plv2-man5
      #- IN: flecs-dopts5
      - IN: tripub-cluster4
      
